assignment-five/myepenpal/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('webtext/', include('webtext.urls')),
    path('admin/', admin.site.urls),
]

assignment-five/webtext/urls.py
from django.urls import path
from . import views

app_name = 'webtext'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.login, name='login'),
    path('<int:pk>/home/', views.UserHomeView.as_view(), name='userHome'),
    path('<int:user_id>/new_message/', views.new_message, name='new_message'),
    path('<int:pk>/success/', views.SuccessView.as_view(), name='success')
]

assignment-five/webtext/models.py
import datetime
from django.db import models
from django.utils import timezone


class User(models.Model):
    username = models.CharField(max_length=30)

    def __str__(self):
        return self.username


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender') # this is the sender
    recipient = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='recipient')
    message_text = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date sent')

    def __str__(self):

assignment-five/webtext/views.py
# from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import User, Message


class IndexView(generic.ListView):
    template_name = 'webtext/index.html'

    def get_queryset(self):
        return HttpResponse("Welcome")


def login(request):
    user, created = User.objects.get_or_create(
        username=request.POST['username'].lower())
    user_id = user.id
    return HttpResponseRedirect(reverse('webtext:userHome', args=(user.id,)))




class UserHomeView(generic.DetailView):
    model = User
    template_name = "webtext/userHome.html"


def new_message(request, user_id):
    message = Message()
    message.user = User.objects.get(id=user_id)
    recipient = User.objects.get_or_create(username=request.POST['receiver'].lower())
    message.recipient = recipient[0]
    message.message_text = request.POST['message']
    message.save()
    return HttpResponseRedirect(reverse('webtext:userHome', args=(message.user.id,)))



class SuccessView(generic.DetailView):
    model = User
    template_name = "webtext/success.html"

assignment-five/webtext/templates/webtext/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My E-Penpal</title>
</head>
<body>
    <h1>Welcome to My E-PenPal!</h1>
    <form name="login" action="{% url 'webtext:login' %}" method="post">
        {% csrf_token %}
        Username: <input type="text" name="username" value=""/><br/>
        <p>*Note: Usernames must be between 3 and 30 characters long.They are not case sensitive.</p>
        <input type="submit" value="login"/>
    </form>
</body>
</html>

assignment-five/webtext/templates/webtext/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
<center>
<h1>Success</h1>

<a href="{% url 'webtext:userHome' user.id %}">
    <input type="button" value="return"/></a>
</center>

</body>
</html>

assignment-five/webtext/templates/webtext/userHome.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    h1, .logout {
        text-align: right;
    }
    h3 {
        text-align: center;

    }
    * {
      box-sizing: border-box;
    }

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 10px;

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>
</head>
<body>
    <h1>Welcome, {{ user.username }}</h1>
    <form class='logout' name="logout" action="{% url 'webtext:index' %}">
        <a href="{% url 'webtext:index' %}"><input type="button" name="logout" value="Sign Out"></a>
    </form><br/>

    <div class="row">
<!--
        <div class="column">
            <h3>Messages Sent To:</h3>
            <ul>
                {% for message in user.sender.all %}
                <li>{{message.recipient.username }} - {{ message.message_text }}</li>
                {% endfor %}
            </ul>

        </div> -->
        <div class="column">
            <h3>Inbox</h3>
            {% for message in user.recipient.all %}
            <b>{{ message.user.username }}</b>          {{ message.message_text }}<br/><br/>
            {% endfor %}

        </div>

        <div class="column">
            <h3>Compose</h3>
            <form name="new_message" action="{% url 'webtext:new_message' user.id %}" method="POST">
                {% csrf_token %}
                To (username): <input type="text" name="receiver"><br/><br/>
                <br/><textarea name="message" rows="10" cols="20"></textarea><br/>
                <input type="submit" value="send new message">
            </form>
        </div>
    </div>
</body>
</html>